---
name: Basic Linting

on:
  pull_request:
    branches: ["**"]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    # - uses: asdf-vm/actions/setup@v3
    # - name: Install tooling required for pre-commit
    #   run: |
    #     for tool in actionlint shellcheck terraform terraform-docs tflint ; do
    #       asdf plugin add "${tool}"
    #       asdf install "${tool}"
    #     done
      # moving actionlint to centralized composite action
    - uses: camunda/infra-global-github-actions/actionlint@main
      with:
        version: '1.7.4'

    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --all-files --verbose
